<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\ScavengeDatabaseCompleted;

use UnexpectedValueException;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.ScavengeDatabaseCompleted.ScavengeResult</code>
 */
class ScavengeResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>InProgress = 1;</code>
     */
    const InProgress = 1;
    /**
     * Generated from protobuf enum <code>Failed = 2;</code>
     */
    const Failed = 2;

    private static $valueToName = [
        self::Success => 'Success',
        self::InProgress => 'InProgress',
        self::Failed => 'Failed',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ScavengeResult::class, \Prooph\EventStoreClient\Messages\ClientMessages\ScavengeDatabaseCompleted_ScavengeResult::class);

