<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\NotHandled;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.NotHandled.NotHandledReason</code>
 */
class NotHandledReason
{
    /**
     * Generated from protobuf enum <code>NotReady = 0;</code>
     */
    const NotReady = 0;
    /**
     * Generated from protobuf enum <code>TooBusy = 1;</code>
     */
    const TooBusy = 1;
    /**
     * Generated from protobuf enum <code>NotMaster = 2;</code>
     */
    const NotMaster = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(NotHandledReason::class, \Prooph\EventStoreClient\Messages\ClientMessages\NotHandled_NotHandledReason::class);
