<?php
/**
 * This file is part of the prooph/event-store-client.
 * (c) 2018-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2018-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\NotHandled;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.NotHandled.NotHandledReason</code>
 */
class NotHandledReason
{
    /**
     * Generated from protobuf enum <code>NotReady = 0;</code>
     */
    const NotReady = 0;
    /**
     * Generated from protobuf enum <code>TooBusy = 1;</code>
     */
    const TooBusy = 1;
    /**
     * Generated from protobuf enum <code>NotMaster = 2;</code>
     */
    const NotMaster = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(NotHandledReason::class, \Prooph\EventStoreClient\Messages\ClientMessages\NotHandled_NotHandledReason::class);
