<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\PersistentSubscriptionNakEvents;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.PersistentSubscriptionNakEvents.NakAction</code>
 */
class NakAction
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>Park = 1;</code>
     */
    const Park = 1;
    /**
     * Generated from protobuf enum <code>Retry = 2;</code>
     */
    const Retry = 2;
    /**
     * Generated from protobuf enum <code>Skip = 3;</code>
     */
    const Skip = 3;
    /**
     * Generated from protobuf enum <code>Stop = 4;</code>
     */
    const Stop = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(NakAction::class, \Prooph\EventStoreClient\Messages\ClientMessages\PersistentSubscriptionNakEvents_NakAction::class);
