<?php

/**
 * This file is part of `prooph/event-store-client`.
 * (c) 2018-2020 Alexander Miertsch <kontakt@codeliner.ws>
 * (c) 2018-2020 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Messages.ClientMessages.ConnectToPersistentSubscription</code>
 */
class ConnectToPersistentSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     */
    private string $subscription_id = '';
    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     */
    private string $event_stream_id = '';
    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     */
    private int $allowed_in_flight_messages = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_id
     *     @type string $event_stream_id
     *     @type int $allowed_in_flight_messages
     * }
     */
    public function __construct($data = null)
    {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @return string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * Generated from protobuf field <code>string subscription_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, true);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @return string
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, true);
        $this->event_stream_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     * @return int
     */
    public function getAllowedInFlightMessages()
    {
        return $this->allowed_in_flight_messages;
    }

    /**
     * Generated from protobuf field <code>int32 allowed_in_flight_messages = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setAllowedInFlightMessages($var)
    {
        GPBUtil::checkInt32($var);
        $this->allowed_in_flight_messages = $var;

        return $this;
    }
}
