<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult instead.
     * @deprecated
     */
    class CreatePersistentSubscriptionCompleted_CreatePersistentSubscriptionResult
    {
    }
}
\class_exists(CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\CreatePersistentSubscriptionCompleted_CreatePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult instead', E_USER_DEPRECATED);
