<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult instead.
     * @deprecated
     */
    class DeletePersistentSubscriptionCompleted_DeletePersistentSubscriptionResult {}
}
class_exists(DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult::class);
@trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\DeletePersistentSubscriptionCompleted_DeletePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult instead', E_USER_DEPRECATED);

