<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Prooph.EventStoreClient.Messages.ClientMessages.DeletePersistentSubscription</code>
 */
class DeletePersistentSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     */
    protected $subscription_group_name = '';
    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     */
    protected $event_stream_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $subscription_group_name
     *     @type string $event_stream_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     * @return string
     */
    public function getSubscriptionGroupName()
    {
        return $this->subscription_group_name;
    }

    /**
     * Generated from protobuf field <code>string subscription_group_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSubscriptionGroupName($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_group_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @return string
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * Generated from protobuf field <code>string event_stream_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_stream_id = $var;

        return $this;
    }

}

