<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\NotHandled\NotHandledReason instead.
     * @deprecated
     */
    class NotHandled_NotHandledReason {}
}
class_exists(NotHandled\NotHandledReason::class);
@trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\NotHandled_NotHandledReason is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\NotHandled\NotHandledReason instead', E_USER_DEPRECATED);

