<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\NotHandled\MasterInfo instead.
     * @deprecated
     */
    class NotHandled_MasterInfo
    {
    }
}
\class_exists(NotHandled\MasterInfo::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\NotHandled_MasterInfo is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\NotHandled\MasterInfo instead', E_USER_DEPRECATED);
