<?php

/**
 * This file is part of `prooph/event-store-client`.
 * (c) 2018-2020 Alexander Miertsch <kontakt@codeliner.ws>
 * (c) 2018-2020 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

use UnexpectedValueException;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.OperationResult</code>
 */
class OperationResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>PrepareTimeout = 1;</code>
     */
    const PrepareTimeout = 1;
    /**
     * Generated from protobuf enum <code>CommitTimeout = 2;</code>
     */
    const CommitTimeout = 2;
    /**
     * Generated from protobuf enum <code>ForwardTimeout = 3;</code>
     */
    const ForwardTimeout = 3;
    /**
     * Generated from protobuf enum <code>WrongExpectedVersion = 4;</code>
     */
    const WrongExpectedVersion = 4;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 5;</code>
     */
    const StreamDeleted = 5;
    /**
     * Generated from protobuf enum <code>InvalidTransaction = 6;</code>
     */
    const InvalidTransaction = 6;
    /**
     * Generated from protobuf enum <code>AccessDenied = 7;</code>
     */
    const AccessDenied = 7;

    private static array $valueToName = [
        self::Success => 'Success',
        self::PrepareTimeout => 'PrepareTimeout',
        self::CommitTimeout => 'CommitTimeout',
        self::ForwardTimeout => 'ForwardTimeout',
        self::WrongExpectedVersion => 'WrongExpectedVersion',
        self::StreamDeleted => 'StreamDeleted',
        self::InvalidTransaction => 'InvalidTransaction',
        self::AccessDenied => 'AccessDenied',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(\sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . \strtoupper($name);
        if (! \defined($const)) {
            throw new UnexpectedValueException(\sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }

        return \constant($const);
    }
}
