<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\PersistentSubscriptionNakEvents\NakAction instead.
     * @deprecated
     */
    class PersistentSubscriptionNakEvents_NakAction
    {
    }
}
\class_exists(PersistentSubscriptionNakEvents\NakAction::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\PersistentSubscriptionNakEvents_NakAction is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\PersistentSubscriptionNakEvents\NakAction instead', E_USER_DEPRECATED);
