<?php

/**
 * This file is part of `prooph/event-store-client`.
 * (c) 2018-2020 Alexander Miertsch <kontakt@codeliner.ws>
 * (c) 2018-2020 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted\ReadAllResult instead.
     * @deprecated
     */
    class ReadAllEventsCompleted_ReadAllResult
    {
    }
}
\class_exists(ReadAllEventsCompleted\ReadAllResult::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted_ReadAllResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted\ReadAllResult instead', E_USER_DEPRECATED);
