<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted\ReadAllResult instead.
     * @deprecated
     */
    class ReadAllEventsCompleted_ReadAllResult {}
}
class_exists(ReadAllEventsCompleted\ReadAllResult::class);
@trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted_ReadAllResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted\ReadAllResult instead', E_USER_DEPRECATED);

