<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted\ReadEventResult instead.
     * @deprecated
     */
    class ReadEventCompleted_ReadEventResult
    {
    }
}
\class_exists(ReadEventCompleted\ReadEventResult::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted_ReadEventResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted\ReadEventResult instead', E_USER_DEPRECATED);
