<?php

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\ScavengeDatabaseCompleted\ScavengeResult instead.
     * @deprecated
     */
    class ScavengeDatabaseCompleted_ScavengeResult
    {
    }
}
\class_exists(ScavengeDatabaseCompleted\ScavengeResult::class);
@\trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\ScavengeDatabaseCompleted_ScavengeResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\ScavengeDatabaseCompleted\ScavengeResult instead', E_USER_DEPRECATED);
