<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages;

if (false) {
    /**
     * This class is deprecated. Use Prooph\EventStoreClient\Messages\ClientMessages\UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult instead.
     * @deprecated
     */
    class UpdatePersistentSubscriptionCompleted_UpdatePersistentSubscriptionResult {}
}
class_exists(UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult::class);
@trigger_error('Prooph\EventStoreClient\Messages\ClientMessages\UpdatePersistentSubscriptionCompleted_UpdatePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Prooph\EventStoreClient\Messages\ClientMessages\UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult instead', E_USER_DEPRECATED);

