<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\ReadStreamEventsCompleted;

use UnexpectedValueException;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.ReadStreamEventsCompleted.ReadStreamResult</code>
 */
class ReadStreamResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NoStream = 1;</code>
     */
    const NoStream = 1;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 2;</code>
     */
    const StreamDeleted = 2;
    /**
     * Generated from protobuf enum <code>NotModified = 3;</code>
     */
    const NotModified = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;

    private static $valueToName = [
        self::Success => 'Success',
        self::NoStream => 'NoStream',
        self::StreamDeleted => 'StreamDeleted',
        self::NotModified => 'NotModified',
        self::Error => 'Error',
        self::AccessDenied => 'AccessDenied',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ReadStreamResult::class, \Prooph\EventStoreClient\Messages\ClientMessages\ReadStreamEventsCompleted_ReadStreamResult::class);

