<?php

/**
 * This file is part of `prooph/event-store-client`.
 * (c) 2018-2020 Alexander Miertsch <kontakt@codeliner.ws>
 * (c) 2018-2020 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted;

use UnexpectedValueException;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.ReadEventCompleted.ReadEventResult</code>
 */
class ReadEventResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NotFound = 1;</code>
     */
    const NotFound = 1;
    /**
     * Generated from protobuf enum <code>NoStream = 2;</code>
     */
    const NoStream = 2;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 3;</code>
     */
    const StreamDeleted = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;

    private static array $valueToName = [
        self::Success => 'Success',
        self::NotFound => 'NotFound',
        self::NoStream => 'NoStream',
        self::StreamDeleted => 'StreamDeleted',
        self::Error => 'Error',
        self::AccessDenied => 'AccessDenied',
    ];

    public static function name($value)
    {
        if (! isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(\sprintf(
                    'Enum %s has no name defined for value %s', self::class, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = self::class . '::' . \strtoupper($name);
        if (! \defined($const)) {
            throw new UnexpectedValueException(\sprintf(
                    'Enum %s has no value defined for name %s', self::class, $name));
        }

        return \constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(ReadEventResult::class, \Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted_ReadEventResult::class);
