<?php
/**
 * This file is part of the prooph/event-store-client.
 * (c) 2018-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2018-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.ReadEventCompleted.ReadEventResult</code>
 */
class ReadEventResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NotFound = 1;</code>
     */
    const NotFound = 1;
    /**
     * Generated from protobuf enum <code>NoStream = 2;</code>
     */
    const NoStream = 2;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 3;</code>
     */
    const StreamDeleted = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(ReadEventResult::class, \Prooph\EventStoreClient\Messages\ClientMessages\ReadEventCompleted_ReadEventResult::class);
