<?php
/**
 * This file is part of the prooph/event-store-client.
 * (c) 2018-2018 prooph software GmbH <contact@prooph.de>
 * (c) 2018-2018 Sascha-Oliver Prolic <saschaprolic@googlemail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessageDtos.proto

namespace Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted;

/**
 * Protobuf type <code>Prooph.EventStoreClient.Messages.ClientMessages.ReadAllEventsCompleted.ReadAllResult</code>
 */
class ReadAllResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NotModified = 1;</code>
     */
    const NotModified = 1;
    /**
     * Generated from protobuf enum <code>Error = 2;</code>
     */
    const Error = 2;
    /**
     * Generated from protobuf enum <code>AccessDenied = 3;</code>
     */
    const AccessDenied = 3;
}

// Adding a class alias for backwards compatibility with the previous class name.
\class_alias(ReadAllResult::class, \Prooph\EventStoreClient\Messages\ClientMessages\ReadAllEventsCompleted_ReadAllResult::class);
